### ISSUE TITLE
Upgrade to latest version of nom

### ISSUE THREAD

**Issue by jonhoo** [ms705/nom-sql#11]
The version of `nom` currently used by `nom-sql` is fairly old. In and of itself, this isn't so bad (though the newer nom presumably has performance and correctness fixes), but it causes some pain with dependencies. Specifically, the old version of num depends on `regex 0.1`, whereas `regex` is now at `0.2` (which is incompatible according to Rust's semver). `regex 0.1` in turn has a bunch of outdated dependencies (compare [0.1](https://github.com/rust-lang/regex/blob/0.1.80/Cargo.toml) to [current](https://github.com/rust-lang/regex/blob/master/Cargo.toml)). These in turn pull in more old dependencies, etc. For crates that *use* `nom-sql` this causes many dependencies to be pulled in twice (one old, one new), which has a detrimental effect on compilation time and space usage.

I know fixing this is a bit annoying, as the nom api has changed a fair bit, but it's probably eventually worth doing.

**Comment by ms705** [comment]
Done as per #14!
