### ISSUE TITLE
No Delete Query?

### ISSUE THREAD

**Issue by ivanceras** [ms705/nom-sql#2]
Hi, your library seem to have a comprehensive structure of queries. I noticed that the `DeleteStatement` is lacking though.

**Comment by ms705** [comment]
Yes, that's correct! We developed this parser for [a project]() that primarily cares about `CREATE TABLE`, `INSERT` and `SELECT` queries.

There is no reason (other than time and resources on our end) for the parser no to support `DELETE` though! The implementation would be a much simpler version of the parse rules for `SELECT`, I think.

**Comment by jonhoo** [comment]
I'm guessing PRs here would be welcome if you have some time to spare @ivanceras! :)

**Comment by ivanceras** [comment]
@jonhoo I would definitely want to pull a PR on this on the next few days. I have almost completed the PR for https://github.com/ms705/nom-sql/issues/4

**Comment by ms705** [comment]
Resolved by #9.
