### ISSUE TITLE
Are all queries processed as lowercase ?

### ISSUE THREAD

**Issue by lovasoa** [ms705/nom-sql#29]
Is this comment still relevant ?

https://github.com/ms705/nom-sql/blob/791c0f5117b6e02c1e3f146cc4a2689ef7da7a54/src/parser.rs#L58-L59

**Comment by ms705** [comment]
Nope, it's not -- `nom_sql` has been case-insensitive for a long time now (but wasn't initially, as `nom` did not support case-insensitive combinators back around v1.0).
