### ISSUE TITLE
Optional multispace when next to parenthesis

### ISSUE THREAD

**Issue by ivanceras** [ms705/nom-sql#3]
These 2 queries
```sql
INSERT INTO user(name, password) VALUES('aaa','xxx');
INSERT INTO user (name, password) VALUES ('aaa','xxx');
```
are both valid, but `nom-sql` only parses the 2nd correctly.
I'm guessing this is a bit of complex to do in `nom`, where the `multispace` becomes optional when `tag!('(')` is in the next few bytes.

https://github.com/ms705/nom-sql/blob/8fe4e92d3c718cc111063b4e5be1d18a26771e51/src/insert.rs#L23-L40

**Comment by ms705** [comment]
No underlying `nom`-related reason, just unawareness on my part that this is permitted!

(`multispace?` generally works fine for an optional space)

**Comment by ivanceras** [comment]
I thought the solution was more complicated than that.
