### ISSUE TITLE
Queries that contain arbitrary bytes cannot be parsed

### ISSUE THREAD

**Issue by lovasoa** [ms705/nom-sql#33]
SQL files can contain any byte sequence. However, this library only exposes a way to parse a rust string (that is, a sequence of unicode codepoints). This makes it impossible to parse some SQL files (such as the wikipedia dumps I am currently working with), as thay contain byte sequences that are not valid utf-8.

The api should expose a function that takes an `&[u8]` instead of an `&str`.

For handling byte sequences that are not valid utf8 in literal strings, I see two possibilities:

 * Using the already existing [`Blob(Vec<u8>)`](https://docs.rs/nom-sql/0.0.4/nom_sql/enum.Literal.html#variant.Blob) (the information that the literal was a string and not a blob would be lost)
 * Using a fault-tolerant utf8 decoder like [`rust-encoding`](https://lifthrasiir.github.io/rust-encoding/encoding/index.html) (invalid characters would be lost).

**Comment by ms705** [comment]
Fixed in #34, I believe?
