### ISSUE TITLE
Upgrade to nom v5

### ISSUE THREAD

**Issue by thomasharmon808** [ms705/nom-sql#52]
`Nom` recently released v5 and `nom-sql` still uses v4. Just wondering if there is a plan to upgrade and what that plan might be.

One thing to note: nom v5's macros were rewritten to use the _streaming_ version of the parsers. My assumption would be that `nom-sql` would only want to deal with _complete_ parsers when upgrading to nom v5. 

Nom has good documentation on upgrading to nom v5 [here](https://github.com/Geal/nom/blob/master/doc/upgrading_to_nom_5.md)

**Comment by spazm** [comment]
Implemented in #53.  This issue can be closed @ms705.
